name: Publish Quarto Project

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          version: 'latest'
        
      - name: Render
        run: quarto render
      
      - name: Deploy
        uses: actions/deploy-pages@v2
