name: Publish Quarto Project

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: rocker/r-ver:4.4.2
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          version: '1.7.13'
        
      - name: Render
        run: quarto render index.qmd
      
      - name: Deploy
        uses: actions/deploy-pages@v2
